### ISSUE TITLE
Roots can be complex

### ISSUE THREAD

**Issue by AliensWithdrawPeople** [dariakhaetskaya/ComputationalMaths#1]
Use some methods to localize roots on the complex plane in epsilon neighborhood. For example you can use [Aberth method](https://en.wikipedia.org/wiki/Aberth_method) or [Durand–Kerner method](https://en.wikipedia.org/wiki/Durand–Kerner_method/).

**Comment by dariakhaetskaya** [comment]
Thanks, Daniel! Roots can definitely be complex, but this is my homework where all roots are considered to be real. My fault I did not mention it in the description. However, I appreciate your involvement and will check out the links you've provided!:)
